# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a599f7f6dbde420ddff039c838bd8e956d59bcfedfd2863789771fd5db977f67d7dbef062e7449d79c5ffa65414335c96719c206cbb10929debd7930b4d7a601

test:
  secret_key_base: cdbc0bbedc9a92b35ac4e820c8072dcaa7da0a1d60be7c64024ded3ef2bf57f8ad57b461bacdabced18801eed7d63e45a63f3e7b18669249ab121fffe462173d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
